version: 1

from: "nfra/kickstart-flavor-php:7.4"
apache_document_root: /opt/docs

command:
  build:
    - "sudo apt-get update && sudo apt-get -y install docker.io"
    - "composer update"

  test:

  scan:
    - "sudo docker run -t  -v /var/run/docker.sock:/var/run/docker.sock -v /opt:/conf -v /opt/docs:/out -e CONFIG_FILE=/conf/watchlist.yml -e STATUS_FILE=/out/security.json nfra/secscanner"