version: 1

from: "nfra/kickstart-flavor-php:7.2"
apache_document_root: /opt/docs

command:
  build:
    - "sudo apt-get update && sudo apt-get -y install docker.io"
    - "composer update"

  test:

  scan:
    - "php bin/run.php"