name: daily-security-scan

on: [push]

#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron: '0 4 * * *'

jobs:
  scan_containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ssh-key: ${{ secrets.SSH_PUB_KEY }}

      - name: Scan images
        run: ./doscan.sh
        env:
          RUDL_VAULT_SECRET_MAIN: ${{ secrets.RUDL_VAULT_SECRET_MAIN }}

      - name: Commit files
        run: |
          ls -l
          echo "wurst" > test.file
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto update"
          git push
